### ISSUE TITLE
C# code to pull data in a tabular format

### ISSUE THREAD

**Issue by kudohs** [intacct/intacct-sdk-net#185]
I am trying to find a sample cs file to pull very basic data (example: customer's name, ID etc.) using Visual Studio. CS files that were provided seem to be generating in Console format. Thanks.

**Comment by kudohs** [comment]
Or it would be nice if it is Json format. Thanks!

**Comment by dylan-holt-sage** [comment]
Hey @kudohs, I'll take a look, but I have a question.

I assume when you say "Console format" that you are referring to print statements on the console (let me know if I am misunderstanding)..... 

Are you asking for a file that takes in data and stores it in a file whether it be .csv or .json?

Depending on the urgency of what you're needing, you can create the file which you need locally and if you'd like to contribute it to our repository, you can raise a PR and we'll review it. 

Otherwise, we have taken note of this and will let you know once we are able to make the changes from our side :)
