### ISSUE TITLE
Pull Recently Modified Items

### ISSUE THREAD

**Issue by jmawebtech** [Intacct/intacct-sdk-net#23]
Hi,

I would like to pull a list of recent modified inventory items and their stock:

SKU - ABC
Stock: 100

SKU - ABC2
Stock: 101

Please send me the ReadByQuery. I assume your inventory is segregated by warehouse. Is it one of these queries?

https://developer.intacct.com/api/inventory-control/

**Comment by jimmymcpeter** [comment]
Most objects have `WHENCREATED` and `WHENMODIFIED` timestamp fields.  You can also look at the [audit trail objects](https://developer.intacct.com/api/company-console/audit-trails/).

As for pulling stock I'm not sure. Maybe someone else can answer that since I'm not an inventory expert.  Maybe ask on the dev group in the community or support may know - [links here](https://developer.intacct.com/support/)
