### ISSUE TITLE
getUserPermissions & Other Functions

### ISSUE THREAD

**Issue by fpmess** [Intacct/intacct-sdk-net#30]
Hello,

I think the answer is "No," but are functions like getUserPermissions and get_applications exposed through the API?  Thanks!

**Comment by jimmymcpeter** [comment]
The issues here are meant to be for the .NET SDK, not questions related to the Sage Intacct API itself.  Did you mean to ask if these functions are part of the SDK?

**Comment by fpmess** [comment]
I'm sorry, I didn't mean API.  I am wondering if these are available in the .NET SDK.  Thanks,

**Comment by jimmymcpeter** [comment]
No worries! I don't believe these two are included out of the box with the SDK.  They can be added as an enhancement or instead of waiting you can write them yourself using the docs for [list subscriptions](https://developer.intacct.com/api/company-console/subscriptions/#list-subscriptions) and [get user effective permissions](https://developer.intacct.com/api/company-console/users/#get-user-effective-permissions).  We also take pull requests ;)

The SDK clients can execute any class implementations of the `IFunction`.  If the `Intacct.SDK.Functions` classes we included with the SDK do not meet your needs (in this case there isn't one), you are always welcome to write your own classes that implement this interface. Check out the [Custom Object Function](https://developer.intacct.com/tools/sdk-net/custom-object-function/) guide for more on this.

**Comment by fpmess** [comment]
Awesome, thanks for the info.  I had already started working with the Custom Object Function, so I'll continue down that route, and I'll also check out those documents you mentioned.  Thanks for the super quick response.  This .NET SDK rocks!

**Comment by jimmymcpeter** [comment]
:)  In the case of the `get_applications` function, you could probably copy the source we have for `getAPISession` and change the values - https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK/Functions/ApiSessionCreate.cs

**Comment by fpmess** [comment]
Oh yeah, that'll be super easy to implement with this example.  Thanks!

**Comment by fpmess** [comment]
I will go ahead and close the "Issue", unless you'd like it left open for enhancement.  Whichever you prefer!

**Comment by jimmymcpeter** [comment]
Eh leave it open so we can track it

**Comment by fpmess** [comment]
I ended up getting these to work.  I created a Pull Request if you'd like to see the additions.  Thanks again for your help.
