### ISSUE TITLE
Poor Error Messages

### ISSUE THREAD

**Issue by rposener** [Intacct/intacct-sdk-net#38]
Hello,

We seem to be having an issue where we cannot get to the bottom of an issue due to [limited error messages returning from the SDK](https://github.com/PracticeEngine/GLIntegration/issues/1) -  I wonder if you would be so kind as to look at our issue and provide us any input?  The error we are getting is:

```txt
PL030000006 Exmployee cannot stop working before he starts
BL010019973 Could not update Employee record!
```

However it does not tell us which record in the batch is actually the problem.  We have verified the data we are submitting does not reflect stop date before start date.

**Comment by mitcrellim** [comment]
My guess is that there is an employee in the batch that already has an end date that is before the start date.

do you have the actual XML response from Intacct logged?  there may be details in there.

**Comment by jimmymcpeter** [comment]
@mitcrellim is correct with the employee's start date being greater than the end date.  Without some sample SDK code of the function you are executing or logged request, we're kinda flying blind here.

**Comment by rposener** [comment]
@jimmymcpeter - that's exactly what we understand, but from our code base (see linked) - we cannot seem to get the actual XML - the data we are feeding into our [project]([https://github.com/PracticeEngine/GLIntegration) seems to all valid/correct.  

I have added NLog with hopes it would capture the XML - but my implementation teammember tells me he's not getting anything.  Can you take a look at [OnlineClient](https://github.com/PracticeEngine/GLIntegration/blob/master/src/PE.Nominal.Intacct/IntacctBaseService.cs#L67-L75) and [NLog Config](https://github.com/PracticeEngine/GLIntegration/blob/master/src/PE.Nominal.Web/Program.cs#L17) and let me know if we need to configure something more to get a Log of the XML data?  

Here is the exact code were are using (sending batches of 50 employee updates or creates at a time) - [IntacctSyncService.SyncOrgEmployees](https://github.com/PracticeEngine/GLIntegration/blob/master/src/PE.Nominal.Intacct/IntacctSyncService.cs#L215-L337)  - This seems to cause the error even though every single employee has a EndDate after startdate (or is not set).

**Comment by jimmymcpeter** [comment]
@rposener I added a comment on your commit [here](https://github.com/PracticeEngine/GLIntegration/commit/c429c3aff4349be2ecc41ff8a5553229d253c67c).

**Comment by rposener** [comment]
@jimmymcpeter thanks - have sent that information to our implementation team.  Once they can test it, perhaps we can find out final story. 

Just thinking about this further, could it be that a user has been re-activated, so their staff record has a terminated date, but now is to been set to a new start in the future, and a blank/null ended date - but it tries to update the start first, and breaks.  Shouldn't a StaffUpdate Function update all fields before validating, or will we need to detect these, set them as active, then update their start date?

**Comment by jimmymcpeter** [comment]
Without access to your environment/data and the sample request, we could only guess at this point.  This is something Sage Intacct's customer/partner support team is equipped to do, since they can access your environment.  At this point, it's really an issue you have with the Sage Intacct API/product config, and not the SDK itself since you'd run into this using any other client sending the same XML request.  Are you able to open cases with support?

**Comment by rposener** [comment]
@jimmymcpeter - thanks for the help.  I will go ahead and close this.  If I have more questions about the logging infrastructure, I might ping you again on that.  I did add a comment that we'd like see the MS Logging Abstractions, so we can maintain a centralized logging framework instead of being tied to NLog for the Intacct portion.  We are just a software company - our customers hire various Intacct partners to setup the integration configs.  We are just providing some common code to help them get data from our system fed into Intacct (or any GL system for that matter).  We are trying to get the relevant partner to take this up with support.

**Comment by jimmymcpeter** [comment]
Ahh so we've got Intacct > Practice Engine > Partner > Customer.  This gets a little difficult if the Partner is the only one able to open support cases.  We'll take a look at the logging framework.

**Comment by rposener** [comment]
Yeah, we have gotten the log details.  Just adding here in case you guys have any insight.  Apparently the partner has not responded in over a week - but hopefully we can work with customer to get it resolved.

```xml
<function controlid="cb47238a-a093-4b67-b351-369a6399a457">
               <update>
                              <EMPLOYEE>
                                             <EMPLOYEEID>16291</EMPLOYEEID>
                                             <PERSONALINFO>
                                                            <CONTACTNAME>removed name</CONTACTNAME>
                                             </PERSONALINFO>
                                             <STARTDATE>02/26/2018</STARTDATE>
                                             <STATUS>active</STATUS>
                                             <DEPARTMENTID>GA</DEPARTMENTID>
                                             <LOCATIONID>TUL</LOCATIONID>
                                             <PE_STAFF_CODE>ADQ</PE_STAFF_CODE>
                                             <RECORDNO>1854</RECORDNO>
                              </EMPLOYEE>
               </update>
</function>
```

based on this - I'm thinking my assumption must be correct - the employee end date must be set, in intacct, but our function is not clearing that.

**Comment by jimmymcpeter** [comment]
So with the way the `<update>` function works in the API, if you want to clear out the end date, you have to pass it as an empty XML element -- `<ENDDATE />`.

The EmployeeUpdate.EndDate property is nullable however I'm looking at the IaXmlWriter.WriteElement() overloaded function and have a concern with it for clearing your date.  Just setting `EndDate = null` won't get it into the update XML but using `EndDate = new DateTime()` will since it uses the default(DateTime) of `1/1/0001 12:00:00 AM`.  Here's a sample passing test

```c#
public class EmployeeUpdateTest : XmlObjectTestHelper
{
	[Fact]
	public void GetXmlTest()
	{
		string expected = @"<?xml version=""1.0"" encoding=""utf-8""?>
<function controlid=""unittest"">
<update>
	<EMPLOYEE>
		<EMPLOYEEID>E1234</EMPLOYEEID>
		<ENDDATE />
	</EMPLOYEE>
</update>
</function>";

		EmployeeUpdate record = new EmployeeUpdate("unittest")
		{
			EmployeeId = "E1234",
			EndDate = new DateTime(),
		};
		this.CompareXml(expected, record);
	}
}
```

**Comment by rposener** [comment]
@jimmymcpeter - is that something you would think of changing the SDK to support setting as null?  Or are you really just suggesting that setting it to DateTime.MinValue (that seems clearer to me than relying on the constructor value which happens to default to same).

This is kind of a headache for us as SQL does not support the same for DateTime, so we will need to create some mappings around dates.  Do strings work the same?  e.g. should we set String.Empty instead of nulls when we need to clear a value?

Thanks for this insight.

**Comment by jimmymcpeter** [comment]
We need to spend some looking at it in more detail.  It might be something for a next major semantic version so we don't break others.  Unfortunately this isn't as straight forward as I'd like it, since the API is not consistent with how an `<update>` works versus `<update_employee>` and nulling out empty elements.  I'd say for you right now with the current version, the default(DateTime) is going to get you the null EndDate.  Alternatively you implement your own `IFunction`.

**Comment by LowryIS** [comment]
@mitcrellim Long shot, but I saw your name on an API test tool for Sage Intacct. Just curious if this is available anywhere for consumption? We are a Sage Intacct customer.

**Comment by tim-miller-sage** [comment]
Was this in a demo or something?  Need to contact you directly to discuss this further.  I don't see a contact email for Lowry IS in our salesforce instance.

**Comment by LowryIS** [comment]
Hi Tim,
We were working with Sage Support as we are using cData to bring in the Sage tables/objects/views into our local SQL environment and had questions about the structure/joins etc..

During the call with Sage they were using your tool and it would really help us in our ERP deployment if we could use a copy of it to gather the details required.

Appreciate any support you can provide. Thanks again.
--Nick.


***@***.***
***@***.***> Spaniola
Information Technology Manager
Corporate Office: <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgoo.gl%2Fmaps%2FC5iWCUzKr3z&data=04%7C01%7Cnicks%40lowrysolutions.com%7C7d89b05dd94440220d1f08d8bc790f53%7C97e56dfc43fc4ab783e10f274a063a9c%7C0%7C0%7C637466575435982599%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CXLCWZhhrf9ABgt1TLrfH8abzUVs1RfaShEsN%2FlVK%2FQ%3D&reserved=0>  9420 Maltby Road * Brighton, MI * 48116<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgoo.gl%2Fmaps%2FC5iWCUzKr3z&data=04%7C01%7Cnicks%40lowrysolutions.com%7C7d89b05dd94440220d1f08d8bc790f53%7C97e56dfc43fc4ab783e10f274a063a9c%7C0%7C0%7C637466575435982599%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CXLCWZhhrf9ABgt1TLrfH8abzUVs1RfaShEsN%2FlVK%2FQ%3D&reserved=0>
Direct:  810-534-1622 | Mobile:  517-410-1095 | Help Desk:  810-534-1714
Web:  www.lowrysolutions.com<https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.lowrysolutions.com%2F&data=04%7C01%7Cnicks%40lowrysolutions.com%7C7d89b05dd94440220d1f08d8bc790f53%7C97e56dfc43fc4ab783e10f274a063a9c%7C0%7C0%7C637466575435992597%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vIxguU9lsYw4N9s2EXEc8%2FHMp%2FPayoHpms%2B1cKsKtLQ%3D&reserved=0>
Please consider the environment before printing this e-mail.
**Notice** Nothing in this communication should be regarded as signed or bearing a signature, electronic or otherwise, unless an expressed statement to the contrary is made.  This communication might contain confidential or other protected information.  If you are not the intended recipient, please notify the sender of your receipt of this communication and then destroy the communication.  State, federal, and other criminal and civil law protects certain electronic and other communications.

**Comment by tim-miller-sage** [comment]
sent you a connect invite on linked in.
