### ISSUE TITLE
CONTACT address update

### ISSUE THREAD

**Issue by glickerman** [Intacct/intacct-sdk-net#70]
Want to update a contact and remove the address completely?  While not something that you will run into alot, it might be needed.  The SDK has a check that says if all fields are blank then do not include those in the function call, and so if you wanted to clear them, you cannot.  I would suggest that this type of functionality to deciding to exclude nodes due to being blank, shouldn't be done.

**Comment by jimmymcpeter** [comment]
Hi @glickerman, if you are unhappy with the provided function classes you are encouraged to implement your own using the `IFunction` interface and/or `AbstractFunction` class.  We felt this was the most appropriate way to address everyone's individual needs instead of forcing you to use all of our own classes.

You could likely clone what exists for the contact classes and then override the [lines here](https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK/Functions/Company/AbstractContact.cs#L83-L88) to compare `AddressLine1 == null` instead of `!string.IsNullOrWhiteSpace(AddressLine1)`.

We can look at pushing down the `WriteXmlMailAddress` function into the CreateContact and UpdateContact classes themselves, but it will likely need to be in a new minor semantic version, like v2.1.
