### ISSUE TITLE
How to add a new line for Rev Rec schedule entry with API

### ISSUE THREAD

**Issue by jtcolvin** [Intacct/intacct-sdk-net#85]
![image](https://user-images.githubusercontent.com/44708183/48789180-740ecf80-ecba-11e8-81ac-cb516f3fbe04.png)

I would like to do the same thing with the API code like on the rev rec edit entry and be able to add a new line - like clicking the plus button.  Any ideas?

**Comment by jimmymcpeter** [comment]
This isn't really a specific question for the SDK itself so I'm going to close this.  Off the top of my head I'm unsure how via the API without more context.  We have some info on [revenue recognition schedules here](https://developer.intacct.com/api/general-ledger/revenue-recognition-schedules/) but it doesn't have adding a line info.  This is honestly a better question for the [Sage Intacct Developers group](https://community.intacct.com/community/0F9i00000005YVbCAM).  You might be better asking [Customer/Partner Support](https://www.sageintacct.com/support) through a case to see if it's supported, since they can also access your company to look at the records and configuration.
