### ISSUE TITLE
Unable to set MEGAENTITYKEY, MEGAENTITYID, and MEGAENTITYNAME when using VendorCreate

### ISSUE THREAD

**Issue by chz160** [Intacct/intacct-sdk-net#88]
When creating a Vendor on a multi-tenant Intacct instance I am unable to set the MegaEntity values (MEGAENTITYKEY, MEGAENTITYID, and MEGAENTITYNAME) on the VendorCreate object. Without these values set the vendor will be created at the "top level" instead of under the correct tenant and will make the record show up as unassigned.

**Comment by jimmymcpeter** [comment]
Those fields are read-only fields set by the system.  You cannot ever change them.

If you want to create a vendor privately within the context of an entity, you can set your credentials with the entity ID piped with the company ID -- `companyId|entityId`.  There's a little section on this [here](https://developer.intacct.com/tools/sdk-net/#cliententity-slide-in-credentials).  I'm noticing this is not very clear, so we're weighing adding an `EntityId` property to the `ClientConfig` instead of making you do piping.

**Comment by chz160** [comment]
The piping of the entityId (locationId?) with the company resolved this issue for me. I misunderstood what the "Client/entity slide-in credentials" documentation was for. Thanks for the clarification.
